#!/bin/bash
PATH="$HOME/.local/bin:$PATH"
export PATH

FGRED="\e[0;31m"
FGREN="\e[0;32m"
FGYEL="\e[0;33m"
FGBLU="\e[0;34m"
FGRES="\e[0;39m"
BGRED="\e[1;41m"
BGREN="\e[1;42m"
BGYEL="\e[1;43m"
BGBLU="\e[1;44m"
BGRES="\e[1;49m"
WARN="\e[5m"
WRES="\e[0m"

_logfile=$PWD/installer.log
_sep="========================="

checkprogram()
{
  command -v $1 >/dev/null 2>&1;
  if [[ $? -eq 1 ]]; then
    echo "${FGRED}Please install $1 before proceeding. ${FGRES}"; 
    exit 1;
  fi
}

case $1 in
	-i)
		echo "${FGREN} Checking program(s)..."
		checkprogram sway
		checkprogram lxappearance
		checkprogram waybar
		checkprogram mako
		checkprogram grim
		checkprogram brightnessctl
		checkprogram wofi
		checkprogram git
		checkprogram kitty
		checkprogram feh
		checkprogram wget
		checkprogram pip
		echo "${FGREN} All dependencies are present on the computer :) ${FGRES}"
		

		echo "${FGREN} Backing up previous dotfile files, if any.. ${FGRES}"
		echo "$_sep" 1>>$_logfile 
		echo ">> BACKUP" 
		mkdir $HOME/.backupdots 1>>$_logfile
		for i in $(ls $PWD/.config); do
			[[ -e $HOME/.config/$i ]] && mv $HOME/.config/$i $HOME/.backupdots
		done
		echo "$_sep" 1>>$_logfile
		

		echo "${FGREN} Installing swaydots"
		echo "$_sep" 1>>$_logfile
		echo ">> COPY" 1>>$_logfile
		cp -r $PWD/.config/* $HOME/.config/ 1>>$_logfile
		cp -r $PWD/.fonts $HOME/ 1>>$_logfile
		echo "$_sep" 1>>$_logfile
		

		echo "${FGREN} Downloading extra dependencies.."
		echo "$_sep" 1>>$_logfile
		echo ">> PIP"
		pip install pywal 1>>$_logfile
		pip install pillow 1>>$_logfile
		pip install wpgtk 1>>$_logfile
		fc-cache
		echo "$_sep" 1>>$_logfile

		
		echo "${FGREN} Installing FlatColor theme, linking dotfiles in wpgtk and applying theme.."
		echo "$_sep" 1>>$_logfile
		echo ">> WPG" 1>>$_logfile
		wpg-install.sh -gi 1>>$_logfile
		echo ">> LN" 1>>$_logfile
		ln -sf $HOME/.config/sway/config.d/colors $HOME/.config/wpg/templates/sway 1>>$_logfile
		ln -sf $HOME/.config/waybar/style.css $HOME/.config/wpg/templates/waybar 1>>$_logfile
		ln -sf $HOME/.config/mako/config $HOME/.config/wpg/templates/mako 1>>$_logfile
		ln -sf $HOME/.config/wpg/wallpapers/* $HOME/.config/wpg/.current 1>>$_logfile
		sch=$(ls $HOME/.config/wpg/schemes)
		usrsch=$(ls $HOME/.config/wpg/schemes | sed "s/arch/$USER/g")
		echo ">> MV" 1>>$_logfile
		mv $HOME/.config/wpg/schemes/$sch $HOME/.config/wpg/schemes/$usrsch 1>>$_logfile
		echo ">> CP" 1>>$_logfile
		cp $PWD/gtk/gtk2 $HOME/.local/share/themes/FlatColor/gtk-2.0/gtkrc 1>>$_logfile
		cp $PWD/gtk/gtk3.0 $HOME/.local/share/themes/FlatColor/gtk-3.0/gtk.css 1>>$_logfile
		cp $PWD/gtk/gtk3.20 $HOME/.local/share/themes/FlatColor/gtk-3.20/gtk.css 1>>$_logfile
		cp $PWD/gtk/gtkrc $HOME/.gtkrc-2.0 1>>$_logfile
		echo ">> GSETTINGS" 1>>$_logfile
		gsettings set org.gnome.desktop.interface gtk-theme 'FlatColor' 1>>$_logfile
		gsettings set org.gnome.desktop.interface icon-theme 'flattrcolor' 1>>$_logfile
		swaymsg reload
		echo "$_sep" 1>>$_logfile

		
		echo "${FGREN} Installing blurlock (required password)"
		echo "$_sep" 1>>$_logfile
		wget https://raw.githubusercontent.com/MuhammedTaha02/swaydots/main/blurlock 1>>$_logfile
	       	sudo mv blurlock /usr/local/bin/blurlock 1>>$_logfile
		sudo chmod +x /usr/local/bin/blurlock 1>>$_logfile
		echo "$_sep" 1>>$_logfile
	;;
	-r)
		echo "${FGYEL} Removing dotfiles and restoring old dotfiles.."
		for r in $(ls $HOME/.backupdots); do
			rm -rf $HOME/.config/$r
			cp -r $HOME/.backupdots/$r $HOME/.config/
		done
	;;
esac
