#!/bin/bash
PATH="$HOME/.local/bin:$PATH"
export PATH
case $1 in
	-i)
		checkprogram sway
		checkprogram lxappearance
		checkprogram waybar
		checkprogram mako
		checkprogram grim
		checkprogram brightnessctl
		checkprogram wofi
		checkprogram git
		mkdir $HOME/.backupdots
		for i in $(ls $PWD/.config); do
			[[ -e $HOME/.config/$i ]] && mv $HOME/.config/$i $HOME/.backupdots
		done
		cp -r $PWD/.config/* $HOME/.config/
		cp -r $PWD/.fonts $HOME/
		pip install pywal
		pip install pillow
		pip install wpgtk
		fc-cache
		wpg-install.sh -gi
		ln -sf $HOME/.config/sway/config.d/colors $HOME/.config/wpg/templates/sway
		ln -sf $HOME/.config/waybar/style.css $HOME/.config/wpg/templates/waybar
		ln -sf $HOME/.config/mako/config $HOME/.config/wpg/templates/mako
		ln -sf $HOME/.config/wpg/wallpapers/* $HOME/.config/wpg/.current
		sch=$(ls $HOME/.config/wpg/schemes)
		usrsch=$(ls $HOME/.config/wpg/schemes | sed "s/arch/$USER/g")
		mv $HOME/.config/wpg/schemes/$sch $HOME/.config/wpg/schemes/$usrsch
		cp $PWD/gtk/gtk2 $HOME/.local/share/themes/FlatColor/gtk-2.0/gtkrc
		cp $PWD/gtk/gtk3.0 $HOME/.local/share/themes/FlatColor/gtk-3.0/gtk.css
		cp $PWD/gtk/gtk3.20 $HOME/.local/share/themes/FlatColor/gtk-3.20/gtk.css
		cp $PWD/gtk/gtkrc $HOME/.gtkrc-2.0
		gsettings set org.gnome.desktop.interface gtk-theme 'FlatColor'
		gsettings set org.gnome.desktop.interface icon-theme 'flattrcolor'
		curl -sS https://raw.githubusercontent.com/MuhammedTaha02/swaydots/main/blurlock | sudo tee /usr/local/bin/blurlock
		sudo chmod +x /usr/local/bin/blurlock
		swaymsg reload
	;;
	-r)
		for r in $(ls $HOME/.backupdots); do
			rm -rf $HOME/.config/$r
			cp -r $HOME/.backupdots/$r $HOME/.config/
		done
	;;
esac

checkprogram()
{
  command -v $1 >/dev/null 2>&1;
  if [[ $? -eq 1 ]]; then
    echo "Please install $1 before proceeding"; 
    exit 1;
  fi
}
