#!/bin/bash
mkdir $HOME/.backupdots
for i in $(ls $PWD/.config); do
	[[ -e $HOME/.config/$i ]] && mv $HOME/.config/$i $HOME/.backupdots
done

cp -r $PWD/.config/* $HOME/.config/
pip install pywal
pip install pillow
pip install wpgtk
wpg-install.sh -gi
ln -sf $HOME/.config/sway/config.d/colors $HOME/.config/wpg/templates/sway
ln -sf $HOME/.config/waybar/style.css $HOME/.config/wpg/templates/waybar
ln -sf $HOME/.config/mako/config $HOME/.config/wpg/templates/mako
